"""Analysis workflow: Deep Research and Flash Briefing.

This module defines the complete Market Analyst Agent graph with:
- Router for intent classification (deep research vs flash briefing)
- Plan-and-Execute + ReAct path (thorough analysis)
- ReWOO path (fast, token-efficient snapshots)
- PostgreSQL checkpointing for state persistence
- Human-in-the-loop interrupts for report approval
"""

import uuid
from datetime import datetime

from langchain_core.messages import HumanMessage
from langchain_core.runnables import RunnableConfig
from langgraph.checkpoint.base import BaseCheckpointSaver
from langgraph.graph import END, StateGraph
from langgraph.graph.state import CompiledStateGraph

from market_analyst.llm import ModelSettings
from market_analyst.memory import (
    DocumentMetadata,
    get_document_memory,
    load_user_profile,
)
from market_analyst.runtime.ownership import serialized_run
from market_analyst.schemas import AgentState, DraftReport, ExecutionMode, UserProfile
from market_analyst.tools.registry import tool_registry
from market_analyst.workflows.research import add_research_nodes
from market_analyst.workflows.research import route_after_executor as route_after_executor
from market_analyst.workflows.research import route_after_router as route_after_router


def create_graph(
    checkpointer: BaseCheckpointSaver | None = None,
    force_mode: ExecutionMode | None = None,
    *,
    nodes: dict | None = None,
) -> CompiledStateGraph:
    """Create the Market Analyst Agent graph.

    Graph Structure:
    ```
    START → router ─┬─→ planner → executor ─┬─→ executor (loop)
                    │                       └─→ reporter ──────────┐
                    │                                              ├─→ publish → END
                    └─→ rewoo_planner → rewoo_worker → rewoo_solver─┘
    ```

    Args:
        checkpointer: Optional PostgresSaver for state persistence.

    Returns:
        Compiled StateGraph ready for invocation.

    Note:
        To force a specific reasoning mode (bypassing the router), set
        ``execution_mode`` on the initial ``AgentState`` instead — the router
        node short-circuits when the mode is already set.
    """
    builder = StateGraph(AgentState)
    add_research_nodes(builder, nodes=nodes)
    builder.add_node("publish", publish_node)
    builder.add_edge("publish", END)

    # Compile with checkpointer and interrupt
    # interrupt_before=["publish"] pauses for human approval
    return builder.compile(
        checkpointer=checkpointer,
        interrupt_before=["publish"],
    )


def publish_node(state: AgentState) -> dict:
    """Final node that publishes the approved report.

    This node runs after human approval (via interrupt_before).
    Saves the report using DocumentMemory in the 'research' namespace.
    The content hash makes retries replace the same archive document.
    """
    if state.error:
        raise ValueError(f"Cannot publish a failed run: {state.error}")
    if state.evaluator_verdict not in {"pass", "needs_human"}:
        raise ValueError("Evaluator rejected this draft; correct the evidence and regenerate")
    if not state.report_approved:
        return {"error": "Report was not approved"}

    if not state.draft_report:
        return {"error": "No report to publish"}

    report = state.draft_report
    mode_suffix = "flash" if state.execution_mode == ExecutionMode.FLASH_BRIEFING else "deep"
    import hashlib

    timestamp = hashlib.sha256((state.user_id + report.model_dump_json()).encode()).hexdigest()[:16]

    # Format report as markdown
    risk_factors = "\n".join(f"- {r}" for r in report.risk_factors)

    content = f"""# {report.title}

**Ticker:** {report.ticker}
**Mode:** {mode_suffix.capitalize()} {"(ReWOO)" if mode_suffix == "flash" else "(ReAct)"}
**Recommendation:** {report.recommendation.upper().replace("_", " ")}
**Confidence:** {report.confidence:.0%}
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

## Summary

{report.summary}

## Analysis

{report.analysis}

## Risk Factors

{risk_factors}

---

*This report was generated by Market Analyst Agent and approved for publication.*
"""

    # Save using DocumentMemory (primary storage)
    doc_memory = get_document_memory()
    key = f"{report.ticker}_{mode_suffix}_{timestamp}"

    metadata = DocumentMetadata(
        timestamp=datetime.now().isoformat(),
        user_id=state.user_id,
        namespace="research",
        tags=["market-analysis", mode_suffix],
        execution_mode=mode_suffix,
        ticker=report.ticker,
    )

    doc_path = doc_memory.write_doc(
        namespace="research",
        key=key,
        content=content,
        metadata=metadata,
    )

    print(f"\n📄 Report saved to document memory: {doc_path}")

    return {
        "report_approved": True,
    }


def _restore_tool_surface(expected_tools, tools):
    if expected_tools is None:
        return tools
    available = tool_registry(tools)
    if tools is not None and set(available) != set(expected_tools):
        raise ValueError("Retry must preserve the saved tool surface")
    if not set(expected_tools) <= available.keys():
        raise ValueError("Retry requires the original custom tools")
    return [available[name] for name in expected_tools]


@serialized_run
def run_analysis(
    query: str,
    user_id: str = "default",
    thread_id: str | None = None,
    checkpointer: BaseCheckpointSaver | None = None,
    force_mode: ExecutionMode | None = None,
    *,
    model_settings: ModelSettings | None = None,
    tools: list | None = None,
    profile_loader=None,
    retry_delivery: bool = False,
    graph_factory=None,
) -> dict:
    """Run a complete stock analysis.

    This is the main entry point for running the agent.

    Args:
        query: User's analysis request (e.g., "Analyze NVDA stock")
        user_id: User identifier for profile lookup
        thread_id: Optional thread ID for resuming a conversation
        checkpointer: Optional checkpointer for persistence
        force_mode: Optional execution mode override

    Returns:
        Final state with draft report
    """
    graph = (graph_factory or create_graph)(checkpointer=checkpointer)
    thread_id = thread_id or str(uuid.uuid4())
    config: RunnableConfig = {"configurable": {"thread_id": thread_id}, "recursion_limit": 60}
    saved = graph.get_state(config) if checkpointer else None
    if saved and saved.values:
        if not retry_delivery:
            raise ValueError("Thread already exists; resume it or use a new thread ID for a new turn")
        if saved.values.get("user_id") != user_id:
            raise ValueError("Run belongs to a different principal")
        original = saved.values.get("messages", [])
        if original and original[0].content != query:
            raise ValueError("Delivery query differs from the saved run")
        tools = _restore_tool_surface(saved.values.get("tool_names"), tools)
        settings = saved.values.get("model_settings") or (model_settings or ModelSettings.from_env()).model_dump()
        config["configurable"]["model_settings"] = settings
        if tools is not None:
            config["configurable"]["tools"] = tools
        # A queue retry must not cross a human-approval interrupt.
        result = saved.values if not saved.next or "publish" in saved.next else graph.invoke(None, config, durability="sync" if checkpointer else None)
    else:
        settings = model_settings or ModelSettings.from_env()
        config["configurable"]["model_settings"] = settings.model_dump()
        if tools is not None:
            config["configurable"]["tools"] = tools
        loader = profile_loader or (load_user_profile if checkpointer else lambda _: UserProfile())
        initial_state = AgentState(
            messages=[HumanMessage(content=query)],
            user_profile=loader(user_id),
            user_id=user_id,
            execution_mode=force_mode,
            model_settings=settings.model_dump(),
            tool_names=list(tool_registry(tools)),
        )
        result = graph.invoke(initial_state, config, durability="sync" if checkpointer else None)
    if error := result.get("error"):
        raise RuntimeError(error)

    return {
        "thread_id": thread_id,
        "state": result,
        "needs_revision": result.get("evaluator_verdict") == "fail",
        "draft_report": result.get("draft_report"),
        "execution_mode": result.get("execution_mode"),
        "requires_approval": checkpointer is not None and not result.get("report_approved", False) and result.get("evaluator_verdict") != "fail",
    }


@serialized_run
def approve_and_publish(
    thread_id: str,
    checkpointer: BaseCheckpointSaver,
    edits: dict | None = None,
) -> dict:
    """Approve the draft report and continue to publish.

    This function implements the HITL approval flow:
    1. Optionally edit the draft report
    2. Mark as approved
    3. Resume the graph to complete

    Args:
        thread_id: The thread ID of the paused analysis
        checkpointer: Checkpointer with the saved state
        edits: Optional dict of report field edits

    Returns:
        Final state after publishing
    """
    graph = create_graph(checkpointer=checkpointer)
    config: RunnableConfig = {"configurable": {"thread_id": thread_id}}

    # Get current state
    current_state = graph.get_state(config)

    if not current_state or not current_state.values:
        raise ValueError(f"No state found for thread {thread_id}. Make sure persistence is enabled when running the analysis.")

    # Check if we're at the right interrupt point
    next_nodes = current_state.next
    if not next_nodes:
        if not current_state.values.get("report_approved"):
            raise ValueError("Analysis is not awaiting report approval")
        return {
            "thread_id": thread_id,
            "state": current_state.values,
            "published": True,
        }
    if "publish" not in next_nodes:
        raise ValueError("Analysis is not awaiting report approval")

    print(f"   📍 Resuming from interrupt (next: {next_nodes})")

    if current_state.values.get("evaluator_verdict") not in {"pass", "needs_human"}:
        raise ValueError("Draft has not passed evaluation; regenerate with sufficient evidence")
    if current_state.values.get("error"):
        raise ValueError("Cannot approve a failed run")
    # Apply edits if provided
    update_values: dict[str, object] = {"report_approved": True}

    if edits and current_state.values.get("draft_report"):
        draft = DraftReport.model_validate(current_state.values["draft_report"])
        allowed_edits = {key: value for key, value in edits.items() if key in DraftReport.model_fields}
        draft = DraftReport.model_validate({**draft.model_dump(), **allowed_edits})
        from market_analyst.runtime.evaluator import evaluate_draft_report

        config["configurable"]["model_settings"] = current_state.values.get("model_settings", {})
        verdict = evaluate_draft_report(draft, evidence=current_state.values.get("evidence", []), config=config)
        if verdict.verdict == "fail":
            raise ValueError("Edited draft failed evaluation")
        update_values.update(draft_report=draft, evaluator_verdict=verdict.verdict, evaluator_reasons=verdict.reasons)

    # Update state and resume
    graph.update_state(config, update_values)

    # Resume execution from the interrupt
    result = graph.invoke(None, config, durability="sync" if checkpointer else None)

    return {
        "thread_id": thread_id,
        "state": result,
        "published": True,
    }
